# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notre_equipe_bdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.CharField(default=' ', max_length=400)),
                ('nomPrenom', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['ordre'],
                'verbose_name': 'notre equipe bdd',
            },
        ),
    ]
