# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fiche_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(default=' ', max_length=400)),
                ('numero_contrat', models.CharField(default=' ', max_length=400)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('denomination_social', models.CharField(default=' ', max_length=400)),
                ('adresse_facturation', models.CharField(default=' ', max_length=400)),
                ('enseigne', models.CharField(default=' ', max_length=400)),
                ('adresse_enseigne', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Les fiches client',
                'ordering': ['numero_client'],
            },
        ),
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_incident_technicien', models.FileField(null=True, upload_to='incident_technicien/')),
                ('commentaire', models.TextField(default=' ')),
                ('date_emmision', models.DateTimeField(null=True)),
                ('nom_technicien', models.CharField(default=' ', max_length=400)),
                ('valider', models.BooleanField(default=False)),
                ('date_validation', models.DateField(null=True)),
                ('archive', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.fiche_client')),
            ],
            options={
                'verbose_name': 'Les incident',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='type_incident_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='type_incident_client/')),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('description', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'verbose_name': "Les types d'incident client",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='type_incident_technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='type_incident_technicien/')),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('description', models.CharField(default=' ', max_length=400)),
                ('prix', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'verbose_name': "Les types d'incident",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='utilisateur_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default=' ', max_length=400)),
                ('admin', models.BooleanField(default=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('prenom', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur client',
                'ordering': ['mail'],
            },
        ),
        migrations.CreateModel(
            name='utilisateur_technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(default=' ', max_length=400)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('prenom', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur technicien',
                'ordering': ['mail'],
            },
        ),
        migrations.CreateModel(
            name='velo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnom', models.CharField(default=' ', max_length=400)),
                ('id_parc', models.CharField(default=' ', max_length=400)),
                ('marque', models.CharField(default=' ', max_length=400)),
                ('modele', models.CharField(default=' ', max_length=400)),
                ('date_velo', models.DateField(null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('numero_cadre', models.CharField(default=' ', max_length=400)),
                ('numero_moteur', models.CharField(default=' ', max_length=400)),
                ('numero_battrie', models.CharField(default=' ', max_length=400)),
                ('numero_bicycode', models.CharField(default=' ', max_length=400)),
                ('numero_gps', models.CharField(default=' ', max_length=400)),
                ('numero_cles_av', models.CharField(default=' ', max_length=400)),
                ('numero_cles_bt', models.CharField(default=' ', max_length=400)),
                ('kilometrage', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Les vélo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_client',
            field=models.ManyToManyField(to='incident.type_incident_client', verbose_name='Liste des incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_technicien',
            field=models.ManyToManyField(to='incident.type_incident_technicien', verbose_name='Liste des incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='velo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.velo'),
        ),
        migrations.AddField(
            model_name='fiche_client',
            name='mes_velo',
            field=models.ManyToManyField(to='incident.velo', verbose_name='Liste des velos'),
        ),
        migrations.AddField(
            model_name='fiche_client',
            name='utilisateur',
            field=models.ManyToManyField(to='incident.utilisateur_client', verbose_name='Liste de utilisateurs'),
        ),
    ]
