# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_emmision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
