# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20181126_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='type_reparation',
            field=models.CharField(choices=[('Panne', 'Panne'), ('Usure', 'Usure'), ('Casse', 'Casse')], max_length=50, null=True),
        ),
    ]
